[plugin]
id = "solace-compiler-plugin"
class = "io.ballerina.lib.solace.compiler.SolaceCompilerPlugin"

[[dependency]]
path = "../compiler-plugin/build/libs/solace-compiler-plugin-@project.version@.jar"
